### ISSUE TITLE
Cannot import connector with boto3-1.9.112

### ISSUE THREAD

**Issue by bluesmoon** [snowflakedb/snowflake-connector-python#164]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.4.3

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Linux-4.4.30-32.54.amzn1.x86_64-x86_64-with-Ubuntu-14.04-trusty

3. What are the component versions in the environment (`pip list`)? 
```
Package                    Version        Location                                   
-------------------------- -------------- -------------------------------------------
APScheduler                3.5.1          
asn1crypto                 0.24.0         
awscli                     1.15.73        
azure-common               1.1.18         
azure-storage-blob         1.5.0          
azure-storage-common       1.4.0          
backcall                   0.1.0          
backports-abc              0.5            
boto3                      1.9.112        
botocore                   1.10.72        
certifi                    2015.4.28      
cffi                       1.12.2         
chardet                    2.2.1          
Click                      7.0            
colorama                   0.2.5          
cryptography               2.6.1          
decorator                  4.4.0          
Django                     1.9            
django-sslify              0.2.7          
docutils                   0.11           
entrypoints                0.3            
future                     0.17.1         
gnureadline                6.3.8          
html5lib                   0.999          
idna                       2.8            
ijson                      2.3            
importlib-metadata         0.8            
invoke                     1.1.1          
ipykernel                  5.1.0          
ipython                    6.5.0          
ipython-genutils           0.2.0          
iso8601                    0.1.12         
jedi                       0.13.3         
Jinja2                     2.7.2          
jmespath                   0.9.4          
jsonschema                 2.6.0          
jupyter-client             4.2.0.dev0     /home/ubuntu/notebook_server/jupyter_client
jupyter-core               4.4.0          
livereload                 2.6.0          
Markdown                   3.0.1          
MarkupSafe                 0.18           
mistune                    0.8.3          
mkdocs                     0.17.4         
mockito                    1.1.0          
nbconvert                  4.3.0.dev0     /home/ubuntu/notebook_server/nbconvert     
nbformat                   4.1.0.dev0     /home/ubuntu/notebook_server/nbformat      
nose                       1.3.7          
notebook                   4.1.0.dev0     /home/ubuntu/notebook_server               
numpy                      1.15.0         
parso                      0.4.0          
path.py                    11.5.0         
pexpect                    4.6.0          
pickleshare                0.7.4          
pip                        19.0.3         
prompt-toolkit             1.0.15         
psutil                     5.4.6          
ptyprocess                 0.6.0          
pyasn1                     0.4.5          
pycall                     2.3.2          
pycparser                  2.19           
pycryptodomex              3.7.3          
pycurl                     7.19.3         
Pygments                   1.6            
pygobject                  3.12.0         
PyGreSQL                   5.0.6          
PyJWT                      1.7.1          
pyodbc                     4.0.23         
pyOpenSSL                  19.0.0         
python-apt                 0.9.3.5ubuntu3 
python-dateutil            2.8.0          
pytz                       2018.9         
PyYAML                     3.13           
pyzmq                      17.1.0         
requests                   2.2.1          
roman                      2.0.0          
rsa                        3.4.2          
s3transfer                 0.2.0          
scipy                      1.1.0          
setuptools                 40.8.0         
simplegeneric              0.8.1          
six                        1.10.0         
snowflake-connector-python 1.7.10         
Sphinx                     1.2.2          
terminado                  0.8.2          
tornado                    4.5.3          
traitlets                  4.3.0.dev0     /home/ubuntu/notebook_server/traitlets     
typing                     3.6.6          
tzlocal                    1.5.1          
ujson                      1.35           
unattended-upgrades        0.1            
urllib3                    1.7.1          
wcwidth                    0.1.7          
XlsxWriter                 1.0.5          
zipp                       0.3.3    
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```
>>> import snowflake.connector as sf
```

5. What did you expect to see?

Expected to see nothing

6. What did you see instead?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/snowflake/connector/__init__.py", line 21, in <module>
    from .connection import SnowflakeConnection
  File "/usr/local/lib/python3.4/dist-packages/snowflake/connector/connection.py", line 40, in <module>
    from .cursor import SnowflakeCursor
  File "/usr/local/lib/python3.4/dist-packages/snowflake/connector/cursor.py", line 29, in <module>
    from .file_transfer_agent import (SnowflakeFileTransferAgent)
  File "/usr/local/lib/python3.4/dist-packages/snowflake/connector/file_transfer_agent.py", line 36, in <module>
    from .remote_storage_util import (SnowflakeFileEncryptionMaterial,
  File "/usr/local/lib/python3.4/dist-packages/snowflake/connector/remote_storage_util.py", line 18, in <module>
    from .s3_util import SnowflakeS3Util
  File "/usr/local/lib/python3.4/dist-packages/snowflake/connector/s3_util.py", line 12, in <module>
    from boto3.s3.transfer import TransferConfig
  File "/usr/local/lib/python3.4/dist-packages/boto3/s3/transfer.py", line 129, in <module>
    from s3transfer.manager import TransferConfig as S3TransferConfig
  File "/usr/local/lib/python3.4/dist-packages/s3transfer/manager.py", line 21, in <module>
    from s3transfer.utils import get_callbacks
  File "/usr/local/lib/python3.4/dist-packages/s3transfer/utils.py", line 27, in <module>
    from botocore.exceptions import ReadTimeoutError
ImportError: cannot import name 'ReadTimeoutError'
```

7. Can you set logging to DEBUG and collect the logs?

```
>>> import snowflake.connector as sf                                                                                                             
2019-04-10 15:56:35,171 - MainThread ssl_wrap_socket.py:84 - inject_into_urllib3() - DEBUG - Injecting ssl_wrap_socket_with_ocsp
2019-04-10 15:56:35,172 - MainThread auth.py:66 - <module>() - DEBUG - cache directory: /home/ubuntu/.cache/snowflake
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/snowflake/connector/__init__.py", line 21, in <module>
    from .connection import SnowflakeConnection
  File "/usr/local/lib/python3.4/dist-packages/snowflake/connector/connection.py", line 40, in <module>
    from .cursor import SnowflakeCursor
  File "/usr/local/lib/python3.4/dist-packages/snowflake/connector/cursor.py", line 29, in <module>
    from .file_transfer_agent import (SnowflakeFileTransferAgent)
  File "/usr/local/lib/python3.4/dist-packages/snowflake/connector/file_transfer_agent.py", line 36, in <module>
    from .remote_storage_util import (SnowflakeFileEncryptionMaterial,
  File "/usr/local/lib/python3.4/dist-packages/snowflake/connector/remote_storage_util.py", line 18, in <module>
    from .s3_util import SnowflakeS3Util
  File "/usr/local/lib/python3.4/dist-packages/snowflake/connector/s3_util.py", line 12, in <module>
    from boto3.s3.transfer import TransferConfig
  File "/usr/local/lib/python3.4/dist-packages/boto3/s3/transfer.py", line 129, in <module>
    from s3transfer.manager import TransferConfig as S3TransferConfig
  File "/usr/local/lib/python3.4/dist-packages/s3transfer/manager.py", line 21, in <module>
    from s3transfer.utils import get_callbacks
  File "/usr/local/lib/python3.4/dist-packages/s3transfer/utils.py", line 27, in <module>
    from botocore.exceptions import ReadTimeoutError
ImportError: cannot import name 'ReadTimeoutError'
```

**Comment by bluesmoon** [comment]
Note downgrading to `boto3-1.9.44` fixes the issue.

**Comment by smtakeda** [comment]
Verified the latest boto3 and botocore worked on Linux CentOS 6 Python 3.4:
```
boto3                      1.9.130 
botocore                   1.12.130
```

**Comment by bluesmoon** [comment]
Thank you.

**Comment by smtakeda** [comment]
Confirmed this combination didn't work:
```
>pip list | grep -E "(s3trans|boto)"
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
boto3                      1.9.130 
botocore                   1.10.72 
s3transfer                 0.2.0   
```
And looks like those are unsupported combination:
```
~>pip install -U boto3==1.9.130 botocore==1.10.72
boto3 1.9.130 has requirement botocore<1.13.0,>=1.12.130, but you'll have botocore 1.10.72 which is incompatible.
s3transfer 0.2.0 has requirement botocore<2.0.0,>=1.12.36, but you'll have botocore 1.10.72 which is incompatible.
```
