### ISSUE TITLE
SNOW-743087: AttributeError: 'AuthByWebBrowser' object has no attribute 'timeout'

### ISSUE THREAD

**Issue by aletisunil** [snowflakedb/snowflake-connector-python#1432]
I'm trying to authenticate using SSO but thrown with some attribute error
AttributeError: 'AuthByWebBrowser' object has no attribute 'timeout'

Code:
conn = snowflake.connector.connect(
    user='###',
    account='###',
    role='###',
    warehouse='###',
    host='##########.snowflakecomputing.com',
    authenticator='externalbrowser'
    )
    
  Error:

  290 self.converter = None
    291 self.__set_error_attributes()
--> 292 self.connect(**kwargs)
    293 self._telemetry = TelemetryClient(self._rest)
...
--> 246 auth_timeout = min(self._rest._connection.login_timeout, auth_instance.timeout)
    247 logger.debug(f"Timeout set to {auth_timeout}")
    249 try:

AttributeError: 'AuthByWebBrowser' object has no attribute 'timeout'

Edit:
It's working in older version (tested on 2.9 version) but facing issue with newer version (3.0.0)

**Comment by LStab15** [comment]
I also get this same error but with the Default Authorization. I've ran this code before and it was previously successful, but now it does not work and shows this error for me:

AttributeError: 'AuthByDefault' object has no attribute 'timeout'

**Comment by yzhu2023** [comment]
Hi I am having the same issue. Did you figure out how to solve it?

**Comment by sfc-gh-aalam** [comment]
Are you facing the same error with newer versions of snowflake connector?

**Comment by aletisunil** [comment]
Haven't tried any new versions, but I was able to solve and get it running by installing 2.9.0 version
**pip install snowflake-connector-python==2.9.0**

**Comment by sfc-gh-aalam** [comment]
Can you elaborate on the setup which led to this behavior. For example, was your authentication successful? Was there any delay between when authentication screen popped up, and when you authenticated. Can you enable logger in `DEBUG` mode?

**Comment by sfc-gh-aalam** [comment]
This is resolved by updating to the latest version.
