### ISSUE TITLE
ImportError: cannot import name 'DEFAULT_CLIENT_PREFECTH_THREADS'

### ISSUE THREAD

**Issue by tyarnell** [snowflakedb/snowflake-connector-python#148]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`Python 3.6.7 :: Anaconda, Inc.`)?

2. What operating system and processor architecture are you using (`Windows-10-10.0.15063-SP0`)?

3. What are the component versions in the environment (`snowflake-connector-python 1.7.4`)? 

4. What did you do?
a) Ran validate.py script available on the [Snowflake documentation](https://docs.snowflake.net/manuals/user-guide/python-connector-install.html)
b) Got error below

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

5. What did you expect to see? `Script should output the current version`

6. What did you see instead? 

```
ImportError                               Traceback (most recent call last)
<ipython-input-4-08526089813f> in <module>
----> 1 import snowflake.connector

~\AppData\Local\Continuum\anaconda3\lib\site-packages\snowflake\connector\__init__.py in <module>
     19 from .version import (VERSION)
     20 from .compat import (TO_UNICODE)
---> 21 from .connection import SnowflakeConnection
     22 from .cursor import DictCursor
     23 from .errors import (

~\AppData\Local\Continuum\anaconda3\lib\site-packages\snowflake\connector\connection.py in <module>
     22 from .auth_okta import AuthByOkta
     23 from .auth_webbrowser import AuthByWebBrowser
---> 24 from .chunk_downloader import (
     25     SnowflakeChunkDownloader,
     26     DEFAULT_CLIENT_PREFETCH_THREADS,

ImportError: cannot import name 'DEFAULT_CLIENT_PREFETCH_THREADS'
```

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by smtakeda** [comment]
Verified the example code worked on Python 3.6.7 downloaded from https://www.python.org/downloads/
```
(a) C:\Users\stakeda>python --version
Python 3.6.7
(a) C:\Users\stakeda>python test.py
3.10.0
```
So looks like not general issue.
Trying anaconda.

**Comment by smtakeda** [comment]
not reproducible.
Does `~\AppData\Local\Continuum\anaconda3\lib\site-packages\snowflake\connector\chunk_downloader.py` exist? If so what is the content?

**Comment by tyarnell** [comment]
It does exist - I got it working after:

1_ uninstalling the ./chunk_downloader.py and ./pycryptodomex.py 
2_ and rebuilding them using the anaconda environment.  
3_ reinstalling the snowflake-python-connector using pip.

It appears I had a bad build of both dependencies...
