### ISSUE TITLE
Snowflake connector stopped working in Google Cloud Function

### ISSUE THREAD

**Issue by AlienDeg** [snowflakedb/snowflake-connector-python#211]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.7.1
2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
```Snowflake Connector for Python Version: 1.8.0, Python Version: 3.7.1, Platform: Linux-4.4-x86_64-with-debian-buster-sid```
3. What are the component versions in the environment (`pip list`)? 
```
Flask==0.12.2
google-cloud-bigquery==1.18.0
google-cloud-storage==1.18.0
gunicorn==19.7.1
requests==2.21.0
pysftp==0.2.9
google-api-python-client==1.7.11
oauth2client==4.1.3
snowflake-connector-python==1.8.0

```
However i tested 1.8.5 1.9.0 and 2.0.0
4. What did you do?
If possible, provide a recipe for reproducing the error.
Program is deployed as Cloud Functon on google cloud. It connects to snowflake, pulls data and uploads to BQ. Right now it can't even connect.
5. What did you expect to see?
get data from snowflake and import it to bigquery. everything works locally, everything worked yesterday.
6. What did you see instead?
First it tries to connect like that 10-15 times
```
tarting new HTTPS connection (1): peapod.east-us-2.azure.snowflakecomputing.com
tarting new HTTPS connection (2): peapod.east-us-2.azure.snowflakecomputing.com
tarting new HTTPS connection (3): peapod.east-us-2.azure.snowflakecomputing.com
```
then it fails with error below

```APIException: asn1crypto.keys.PublicKeyInfo().unwrap() has been removed, please use oscrypto.asymmetric.PublicKey().unwrap() instead During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/snowflake/connector/network.py", line 790, in _request_exec auth=SnowflakeAuth(token), File "/env/local/lib/python3.7/site-packages/botocore/vendored/requests/sessions.py", line 465, in request resp = self.send(prep, **send_kwargs) File "/env/local/lib/python3.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send r = adapter.send(request, **kwargs) File "/env/local/lib/python3.7/site-packages/botocore/vendored/requests/adapters.py", line 370, in send timeout=timeout File "/env/local/lib/python3.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen body=body, headers=headers) File "/env/local/lib/python3.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 341, in _make_request self._validate_conn(conn) File "/env/local/lib/python3.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn conn.connect() File "/env/local/lib/python3.7/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 238, in connect ssl_version=resolved_ssl_version) File "/env/local/lib/python3.7/site-packages/snowflake/connector/ssl_wrap_socket.py", line 395, in ssl_wrap_socket_with_ocsp ).validate(server_hostname, ret.connection) File "/env/local/lib/python3.7/site-packages/snowflake/connector/ocsp_snowflake.py", line 996, in validate return self._validate(hostname, cert_data, telemetry_data, do_retry, no_exception) File "/env/local/lib/python3.7/site-packages/snowflake/connector/ocsp_snowflake.py", line 1002, in _validate cert_data, telemetry_data, hostname, do_retry=do_retry) File "/env/local/lib/python3.7/site-packages/snowflake/connector/ocsp_snowflake.py", line 1184, in _validate_certificates_sequential issuer, subject, telemetry_data, hostname, do_retry=do_retry) File "/env/local/lib/python3.7/site-packages/snowflake/connector/ocsp_snowflake.py", line 1153, in validate_by_direct_connection err = self.verify_fail_open(ex, telemetry_data) File "/env/local/lib/python3.7/site-packages/snowflake/connector/ocsp_snowflake.py", line 1166, in verify_fail_open if ex_obj.errno is ER_SERVER_CERTIFICATE_REVOKED: AttributeError: 'APIException' object has no attribute 'errno' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/snowflake/connector/network.py", line 640, in _request_exec_wrapper **kwargs) File "/env/local/lib/python3.7/site-packages/snowflake/connector/network.py", line 883, in _request_exec raise RetryRequest(err) snowflake.connector.network.RetryRequest: 'APIException' object has no attribute 'errno' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 346, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 217, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 210, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 24, in peapod_snowflake snwflk.connect(user='dipla_ga', password='P3op0d#@',account='peapod.east-us-2.azure') File "/user_code/utils/snwflk.py", line 15, in connect account=account File "/env/local/lib/python3.7/site-packages/snowflake/connector/__init__.py", line 33, in Connect return SnowflakeConnection(**kwargs) File "/env/local/lib/python3.7/site-packages/snowflake/connector/connection.py", line 187, in __init__ self.connect(**kwargs) File "/env/local/lib/python3.7/site-packages/snowflake/connector/connection.py", line 484, in connect```

**Comment by AlienDeg** [comment]
it works with adding ```asn1crypto==0.24.0``` to the requirements
